rules:
  - id: subprocess-shell-true
    pattern: subprocess.Popen(..., shell=True)
    message: shell=True может привести к RCE. Используй безопасные альтернативы.
    languages: [python]
    severity: ERROR
