name: DefectDojo Security CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  sast:
    name: Static Code Analysis (Bandit)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit
        
    - name: Install Safety
      run: pip install Safety

    - name: Run Safety check
      run: |
        safety check || true

    - name: Run Bandit
      run: |
        bandit -r dojo -f json -o bandit-report.json || true
        
    - name: Upload Bandit report
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report
        path: bandit-report.json

    - name: Install Semgrep
      run: pip install semgrep
  
    - name: Run Semgrep (custom rules)
      run: |
          semgrep --config=p/ci \
                  --config=.github/.semgrep/custom-rules \
                  --json --output semgrep.json || true
  
    - name: Upload Semgrep report
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-report
        path: semgrep.json

    - name: Install Gitleaks
      run: |
            curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.1/gitleaks_8.18.1_linux_x64.tar.gz | tar -xz
            sudo mv gitleaks /usr/local/bin/

    - name: Run Gitleaks
      run: gitleaks detect --source=. --report-format=json --report-path=gitleaks.json || true

    - name: Upload Gitleaks report
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report
        path: gitleaks.json
