name: DefectDojo Security CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  sast:
    name: Static Code Analysis (Bandit)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit
        
    - name: Install Safety
      run: pip install Safety

    - name: Run Safety check
      run: |
        safety check || true

    - name: Run Bandit
      run: |
        bandit -r dojo -f html -o bandit-report.html || true
        
    - name: Upload Bandit report
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report
        path: bandit-report.html

    - name: Install Semgrep
      run: pip install semgrep
  
    - name: Run Semgrep (custom rules)
      run: |
          semgrep --config=p/ci \
                  --config=.github/.semgrep/custom-rules \
                  --sarif --output semgrep.sarif || true
  
    - name: Upload Semgrep report
      uses: actions/upload-artifact@v4
      with:
          name: semgrep-report
          path: semgrep.sarif

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      with:
        args: detect --source=. --report-format sarif --report-path=gitleaks.sarif 

    - name: Upload Gitleaks report
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report
        path: gitleaks.sarif
